# Generated by Django 4.1.3 on 2023-01-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя скважины')),
                ('oil_count', models.IntegerField(max_length=11, verbose_name='Накоплено нефти')),
                ('days', models.IntegerField(max_length=11, verbose_name='Дней в работе')),
                ('q_oil', models.IntegerField(max_length=11, verbose_name='Дебит нефти')),
                ('wct', models.IntegerField(max_length=11, verbose_name='Обводненность')),
                ('bottom_perf', models.IntegerField(max_length=11, verbose_name='Верх перфорации')),
                ('top_perf', models.IntegerField(max_length=11, verbose_name='Низ перфорации')),
                ('x', models.IntegerField(max_length=11, verbose_name='X')),
                ('y', models.IntegerField(max_length=11, verbose_name='Y')),
            ],
        ),
    ]
