# Generated by Django 4.1.3 on 2023-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wells',
            options={'verbose_name': 'Скважина', 'verbose_name_plural': 'Скважины'},
        ),
        migrations.AlterField(
            model_name='wells',
            name='bottom_perf',
            field=models.FloatField(max_length=11, verbose_name='Верх перфорации'),
        ),
        migrations.AlterField(
            model_name='wells',
            name='top_perf',
            field=models.FloatField(max_length=11, verbose_name='Низ перфорации'),
        ),
        migrations.AlterField(
            model_name='wells',
            name='wct',
            field=models.FloatField(max_length=11, verbose_name='Обводненность'),
        ),
    ]
