# Generated by Django 4.1.3 on 2023-01-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_wells_oil_count_alter_wells_x_alter_wells_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statin_no', models.IntegerField(verbose_name='Номер станции')),
                ('location', models.CharField(max_length=255, verbose_name='Расположение станции')),
                ('well_count', models.IntegerField(verbose_name='Количество вышек')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
