# Generated by Django 4.1.3 on 2023-01-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AddField(
            model_name='wells',
            name='id_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.station'),
            preserve_default=False,
        ),
    ]
