# Generated by Django 4.1.3 on 2023-01-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_station_options_wells_id_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='statin_no',
            new_name='station_no',
        ),
    ]
