# Generated by Django 4.1.3 on 2023-01-31 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rename_id_station_wells_station_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='director_id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'director'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
