# Generated by Django 4.1.2 on 2023-02-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0011_alter_station_director_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
