# Generated by Django 4.1.3 on 2023-03-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_station_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wells',
            name='q_oil',
        ),
        migrations.CreateModel(
            name='Well_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_oil', models.IntegerField(verbose_name='Дебит нефти')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wells')),
            ],
        ),
    ]
