# Generated by Django 4.1.3 on 2023-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_wells_q_oil_well_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well_data',
            options={'verbose_name': 'Дебит нефти', 'verbose_name_plural': 'Дебит нефти'},
        ),
        migrations.AlterField(
            model_name='well_data',
            name='q_oil',
            field=models.FloatField(verbose_name='Дебит нефти'),
        ),
    ]
