# Generated by Django 4.1.3 on 2023-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_well_data_options_alter_well_data_q_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
