# Generated by Django 4.1.3 on 2023-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_date_well_data_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well_data',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
